# Generated by Django 5.2.14 on 2026-05-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('COMMENT', 'comment'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UPDATED', 'Task Updated'), ('PROJECT_CREATED', 'Project Created')], default='COMMENT', max_length=50),
        ),
    ]
